### ISSUE TITLE
Code on GitHub

### ISSUE THREAD

**Issue by mikemayuare** [PacktPublishing/Mastering-spaCy#15]
It seems that almost every chapter in the repository have missing code, is there any plans to update the repo with some notebooks with all the books's code?

Thank you, I'm loving the book.

**Comment by DuyguA** [comment]
> It seems that almost every chapter in the repository have missing code, is there any plans to update the repo with some notebooks with all the books's code?
> 
> Thank you, I'm loving the book.

Hellos, first of all thanks for the question. This repo isn't meant to include all the code from the book, some examples per early chapters; then data and code for the chapters that include mini-projects. I believe small code segments in early chapters are copy-pasteable :relaxed: 

Glad you enjoyed the book, currently I'm making giveaway for a Generative AI book, would you be interested?

**Comment by mikemayuare** [comment]
Is the one on your linkedin? Already commented on it.

Thank you very much

**Comment by DuyguA** [comment]
> Is the one on your linkedin? Already commented on it.
> 
> Thank you very much

yes :wink:
