### ISSUE TITLE
Lemmatization in NLU

### ISSUE THREAD

**Issue by zebrassimo** [PacktPublishing/Mastering-spaCy#4]
Hi Duygu, in the book mastering spaCy, page 46, chapter 2 we have the following code:
```python
import spacy
from spacy.symbols import ORTH, LEMMA
nlp=spacy.load('en')
special_case = [{ORTH: "Angeltown", LEMMA: "Los Angeles"}]
nlp.tokenizer.add_special_case(u'Angeltown',special_case)
doc=nlp(u'I am flying to Angeltown')
for token in doc:
    print(token.text, token.lemma_)
```
trying to import the language model en by
```python
python -m spacy download en
```
 doesn't work:

__As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the full pipeline package name 'en_core_web_sm' instead.__

Not sure if
```python 
special_case = [{ORTH: "Angeltown", LEMMA: "Los Angeles"}]
nlp.tokenizer.add_special_case(u'Angeltown',special_case)
```
fails with __Unable to set attribute 'LEMMA' in tokenizer exception for 'Angeltown'. Tokenizer exceptions are only allowed to specify ORTH and NORM__ because of that.

However this get's the job done:
```python
import spacy
from spacy.symbols import ORTH, LEMMA, NORM
nlp=spacy.load('en_core_web_md')
special_case = [{ORTH: "Angeltown", NORM: "Los Angeles"}]
nlp.tokenizer.add_special_case(u'Angeltown',special_case)
doc=nlp(u'I am flying to Angeltown')
for token in doc:
    print(token.text, token.lemma_)
```
Thanks for the good book!

**Comment by DuyguA** [comment]
I wrote some chapters before v3. I made a second pass to the code after v3 came out, some of the code might have escaped from my attention. Thanks for reporting!

**Comment by RAravindDS** [comment]
> Hi Duygu, in the book mastering spaCy, page 46, chapter 2 we have the following code:
> 
> ```python
> import spacy
> from spacy.symbols import ORTH, LEMMA
> nlp=spacy.load('en')
> special_case = [{ORTH: "Angeltown", LEMMA: "Los Angeles"}]
> nlp.tokenizer.add_special_case(u'Angeltown',special_case)
> doc=nlp(u'I am flying to Angeltown')
> for token in doc:
>     print(token.text, token.lemma_)
> ```
> 
> trying to import the language model en by
> 
> ```python
> python -m spacy download en
> ```
> 
> doesn't work:
> 
> **As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the full pipeline package name 'en_core_web_sm' instead.**
> 
> Not sure if
> 
> ```python
> special_case = [{ORTH: "Angeltown", LEMMA: "Los Angeles"}]
> nlp.tokenizer.add_special_case(u'Angeltown',special_case)
> ```
> 
> fails with **Unable to set attribute 'LEMMA' in tokenizer exception for 'Angeltown'. Tokenizer exceptions are only allowed to specify ORTH and NORM** because of that.
> 
> However this get's the job done:
> 
> ```python
> import spacy
> from spacy.symbols import ORTH, LEMMA, NORM
> nlp=spacy.load('en_core_web_md')
> special_case = [{ORTH: "Angeltown", NORM: "Los Angeles"}]
> nlp.tokenizer.add_special_case(u'Angeltown',special_case)
> doc=nlp(u'I am flying to Angeltown')
> for token in doc:
>     print(token.text, token.lemma_)
> ```
> 
> Thanks for the good book!

HI, This is not working properly, we changed to norm, not lemmas(entire topic is changing bro) 


![image](https://user-images.githubusercontent.com/85152278/160221522-b48a41ce-22fe-45d7-a42e-985620295163.png)
