### ISSUE TITLE
Chapter 4 [os error "en" model and it takes only two positions] 

### ISSUE THREAD

**Issue by RAravindDS** [PacktPublishing/Mastering-spaCy#9]
![image](https://user-images.githubusercontent.com/85152278/161361191-ca4c8ff9-bfab-43d1-af50-4ec2cc0790d3.png)

This is the error, I have solved this using three things. 
1. instead of using model 'en' we can use the "en_core_web_md" model. 
2. You will get another error like it take only 2 positions but you have given 3. for that just remove the none. 
3. You will get another error like list of dictionary not needed, you can enclose the matcher pattern inside the two dimension array(like nested list) 

Here's my code! 

![image](https://user-images.githubusercontent.com/85152278/161361269-2d46b0bf-afb9-4495-8d36-1d56a8d6088b.png)

**Comment by DuyguA** [comment]
Should be fixed in the new versions, still thanks for the report :wave:

**Comment by RAravindDS** [comment]
@DuyguA Thank you so much!
